[package]
name = "Lisp_Interpreter"
version = "0.1.0"
authors = ["SomsTech <50029711+SomsTech@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
